version: '3.3'

services:
  db-microservices:
    image: mysql:8.0.29
    restart: always
    environment:
      # Database Name
      #MYSQL_DATABASE: 'databaseName'
      # Acesso padr達o (N達o obrigatorio)
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'mysql'
      # Acesso Root (Necessario para criar database se n達o existir)
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Porta local exposta> : <Porta no container exposta>
      - '3306:3306'
    expose:
      # Abrir porta X no container
      - '3306'
      # Onde nossos dados ser達o persistidos
    volumes:
      - vol-db-microservices:/var/lib/mysql
    networks:
      - alura-food-network

  rabbitmq:
    build:
      context: .
      dockerfile: dockerfile-rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672" #Porta do host (localhost:15673) : Porta no container
      - "61614:61612"
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - vol-rabbitmq:/var/lib/rabbitmq
      - vol-rabbitmq-plugins:/var/lib/rabbitmq/enabled_plugins
    networks:
      - alura-food-network

volumes:
  vol-db-microservices:
  vol-rabbitmq:
  vol-rabbitmq-plugins:

networks:
  alura-food-network:
    driver: bridge